FROM metabase/metabase:v0.63.16@sha256:c6dd0c6a7861a612aab5825a7fd4236d803883a1c1227715bf41c0948c3cde82

COPY .practice-planner/entrypoint.sh /app/practice-planner-entrypoint.sh
ENTRYPOINT ["/bin/sh", "/app/practice-planner-entrypoint.sh"]
